"""Databento utilities."""

VENUE_FROM_INT = {
    1: "GLBX",
    2: "XNAS",
    3: "XBOS",
    4: "XPSX",
    5: "BATS",
    6: "BATY",
    7: "EDGA",
    8: "EDGX",
    9: "XNYS",
    10: "XCIS",
    11: "XASE",
    12: "ARCX",
    13: "XCHI",
    14: "IEXG",
    15: "FINN",
    16: "FINC",
    17: "FINY",
    18: "MEMX",
    19: "EPRL",
    20: "AMXO",
    21: "XBOX",
    22: "XCBO",
    23: "EMLD",
    24: "EDGO",
    25: "GMNI",
    26: "XISX",
    27: "MCRY",
    28: "XMIO",
    29: "ARCO",
    30: "OPRA",
    31: "MPRL",
    32: "XNDQ",
    33: "XBXO",
    34: "C2OX",
    35: "XPHL",
    36: "BATO",
    37: "MXOP",
    38: "IFEU",
    39: "NDEX",
    40: "DBEQ",
    41: "SPHR"
}

DATASET_FROM_INT = {
    1: "GLBX.MDP3",
    2: "XNAS.ITCH",
    3: "XBOS.ITCH",
    4: "XPSX.ITCH",
    5: "BATS.PITCH",
    6: "BATY.PITCH",
    7: "EDGA.PITCH",
    8: "EDGX.PITCH",
    9: "XNYS.PILLAR",
    10: "XCIS.PILLAR",
    11: "XASE.PILLAR",
    12: "XCHI.PILLAR",
    13: "XCIS.BBO",
    14: "XCIS.TRADES",
    15: "MEMX.MEMOIR",
    16: "EPRL.DOM",
    17: "FINN.NLS",
    18: "FINY.TRADES",
    19: "OPRA.PILLAR",
    20: "DBEQ.BASIC",
    21: "ARCX.PILLAR",
    22: "IEXG.TOPS",
    23: "DBEQ.PLUS",
    24: "XNYS.BBO",
    25: "XNYS.TRADES",
    26: "XNAS.QBBO",
    27: "XNAS.NLS",
    28: "IFEU.IMPACT",
    29: "NDEX.IMPACT"
}

PUBLISHER_FROM_INT = {
    1: "GLBX.MDP3.GLBX",
    2: "XNAS.ITCH.XNAS",
    3: "XBOS.ITCH.XBOS",
    4: "XPSX.ITCH.XPSX",
    5: "BATS.PITCH.BATS",
    6: "BATY.PITCH.BATY",
    7: "EDGA.PITCH.EDGA",
    8: "EDGX.PITCH.EDGX",
    9: "XNYS.PILLAR.XNYS",
    10: "XCIS.PILLAR.XCIS",
    11: "XASE.PILLAR.XASE",
    12: "XCHI.PILLAR.XCHI",
    13: "XCIS.BBO.XCIS",
    14: "XCIS.TRADES.XCIS",
    15: "MEMX.MEMOIR.MEMX",
    16: "EPRL.DOM.EPRL",
    17: "FINN.NLS.FINN",
    18: "FINN.NLS.FINC",
    19: "FINY.TRADES.FINY",
    20: "OPRA.PILLAR.AMXO",
    21: "OPRA.PILLAR.XBOX",
    22: "OPRA.PILLAR.XCBO",
    23: "OPRA.PILLAR.EMLD",
    24: "OPRA.PILLAR.EDGO",
    25: "OPRA.PILLAR.GMNI",
    26: "OPRA.PILLAR.XISX",
    27: "OPRA.PILLAR.MCRY",
    28: "OPRA.PILLAR.XMIO",
    29: "OPRA.PILLAR.ARCO",
    30: "OPRA.PILLAR.OPRA",
    31: "OPRA.PILLAR.MPRL",
    32: "OPRA.PILLAR.XNDQ",
    33: "OPRA.PILLAR.XBXO",
    34: "OPRA.PILLAR.C2OX",
    35: "OPRA.PILLAR.XPHL",
    36: "OPRA.PILLAR.BATO",
    37: "OPRA.PILLAR.MXOP",
    38: "IEXG.TOPS.IEXG",
    39: "DBEQ.BASIC.XCHI",
    40: "DBEQ.BASIC.XCIS",
    41: "DBEQ.BASIC.IEXG",
    42: "DBEQ.BASIC.EPRL",
    43: "ARCX.PILLAR.ARCX",
    44: "XNYS.BBO.XNYS",
    45: "XNYS.TRADES.XNYS",
    46: "XNAS.QBBO.XNAS",
    47: "XNAS.NLS.XNAS",
    48: "DBEQ.PLUS.XCHI",
    49: "DBEQ.PLUS.XCIS",
    50: "DBEQ.PLUS.IEXG",
    51: "DBEQ.PLUS.EPRL",
    52: "DBEQ.PLUS.XNAS",
    53: "DBEQ.PLUS.XNYS",
    54: "DBEQ.PLUS.FINN",
    55: "DBEQ.PLUS.FINY",
    56: "DBEQ.PLUS.FINC",
    57: "IFEU.IMPACT.IFEU",
    58: "NDEX.IMPACT.NDEX",
    59: "DBEQ.BASIC.DBEQ",
    60: "DBEQ.PLUS.DBEQ",
    61: "OPRA.PILLAR.SPHR"
}


__all__ = [
    "VENUE_FROM_INT",
    "DATASET_FROM_INT",
    "PUBLISHER_FROM_INT"
]
